parameter_publisher:
  ros__parameters:
    # ESP32に渡すためのパラメータ (ESP32既定値と一致させること)
    wheel_radius: 0.0391
    wheel_base: 0.39

    rkp: 40.0
    rki: 150.0
    rkd: 0.4
    lkp: 40.0
    lki: 150.0
    lkd: 0.4